name: CI
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP - ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Run PHPCS
      if: matrix.php-versions == '7.4'
      run: vendor/bin/php-cs-fixer --diff -v fix src --using-cache no

    - name: Run PSALM
      if: matrix.php-versions == '7.4'
      run: vendor/bin/psalm --show-info=true --long-progress

    - name: Run PHPMD
      if: matrix.php-versions == '7.4'
      run: vendor/bin/phpmd --exclude Tests/Fixtures src/ text phpmd.xml

    - name: Run PHPA
      if: matrix.php-versions == '7.4'
      run: vendor/bin/phpa src

    - name: Run PHPCPD
      if: matrix.php-versions == '7.4'
      run: vendor/bin/phpcpd --exclude Tests --exclude MethodBuilder src/

    - name: Run PHPUnit - ${{ matrix.php-versions }}
      run: vendor/bin/phpunit
